version: '3.4'
services:
  db:
    image: postgres:10
    container_name: drf_db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
      - "drf-pgdata:/var/lib/postgresql/data"

  minio:
    image: minio/minio:RELEASE.2019-02-14T00-21-45Z
    container_name: drf_s3
    environment:
      MINIO_ACCESS_KEY: ${S3_ACCESS_KEY}
      MINIO_SECRET_KEY: ${S3_SECRET_KEY}
    volumes:
      - "minio-data:/data"
      - "minio-config:/root/.minio"
    command: server /data

volumes:
  drf-pgdata:
  minio-data:
  minio-config:
