# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-20 10:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='upload',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='user',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
